# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'InstagramCloneFirebase' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

pod 'FirebaseUI/Analytics'
pod 'FirebaseUI/Auth'
pod 'FirebaseUI/Core'
pod 'FirebaseUI/Firestore'
pod 'FirebaseUI/Storage'


  # Pods for InstagramCloneFirebase

end
